#27511 add elmah.io blog post
postsharp/postsharp.github.io pull request #5
Opened 2020-09-23 11:56 UTC by Soothsilver

2020-10-01 09:47 UTC, gfraiteur requested changes
Good article, but do more for SEO and for campaign tracking in Google Analyics. Ask Lejla.

2020-10-01 09:47 UTC, gfraiteur commented on _posts/2020-09-23-elmahio.md
> +To set it up, you'll need to [get a license](https://www.postsharp.net/download) and install it in your application. One way to install it is using [our Visual Studio extension](https://marketplace.v
Don't say that you need to get a license because it's no longer true in 6.8.

2020-10-01 09:47 UTC, gfraiteur commented on _posts/2020-09-23-elmahio.md
> +**[elmah.io](https://elmah.io/)** is a cloud-based error monitoring service. Your application functions as a client that sends warnings and errors over the internet to elmah.io servers and you, as th
I would suggest adding Google Analytics query string params sp they can track traffic source.

2020-10-01 09:47 UTC, gfraiteur commented on _posts/2020-09-23-elmahio.md
> +
To the article posted by Elmah.io, add Google Analytics query string parameters for campaign tracking (ask Lejla). Adda hyperlink to "a .NET library for detailed logging". This is good for SEO and that's one of the reasons we're writing the article.

2020-10-01 16:12 UTC, Soothsilver commented on _posts/2020-09-23-elmahio.md
> +To set it up, you'll need to [get a license](https://www.postsharp.net/download) and install it in your application. One way to install it is using [our Visual Studio extension](https://marketplace.v
It is true in 6.7.9, which is what we're releasing now, and 6.8 is not in sight. We just added the ability to get it from the installer but you still need it.

2020-10-01 16:14 UTC, Soothsilver commented on _posts/2020-09-23-elmahio.md
> +**[elmah.io](https://elmah.io/)** is a cloud-based error monitoring service. Your application functions as a client that sends warnings and errors over the internet to elmah.io servers and you, as th
Added

2020-10-02 13:06 UTC, gfraiteur approved these changes

2020-10-02 13:06 UTC, gfraiteur commented on _posts/2020-09-23-elmahio.md
> +
Ok, I assume that elmah will add the utm parameters to us. I don't see them here.

2020-10-02 13:09 UTC, Soothsilver commented on _posts/2020-09-23-elmahio.md
> +
Yes, because we don't want the utm parameters on the blog post when we publish it on our own blog.

2020-10-02 13:10 UTC, merged