#27512 Blog post about PostSharp Logging and Conveyor
postsharp/postsharp.github.io pull request #7
Opened 2020-09-25 08:31 UTC by Soothsilver

2020-10-01 09:58 UTC, gfraiteur requested changes

2020-10-01 09:58 UTC, gfraiteur commented on _posts/2020-09-25-conveyor.md
> +title: "Improved debugging with Conveyor and PostSharp Logging"
```suggestion
title: "Diagnosing webhooks on your development machine with Conveyor and PostSharp Logging"
```

2020-10-01 09:58 UTC, gfraiteur commented on _posts/2020-09-25-conveyor.md
> +---
Start framing the problem. Why is it a hard problem? The reason is that we're doing a webhook and that we want to test in a real situation, where it is called from outside and we can't configure the firewall to get an input port. And also, the webhook originator will not allow the hook to run for more than 20 seconds, so debugging is not an option.

An article should tell a story where the reader is the hero, so you first imagine a situation, frame the problem by telling why it's hard, then you get your two helper characters, Conveyor and PostSharp Logging, enabling the reader to get success.

2020-10-01 09:58 UTC, gfraiteur commented on _posts/2020-09-25-conveyor.md
> +---
Ah ok now I read you've moved away from the webhook idea. Well, anyway the framing should be done in the intro, not later.

2020-10-01 16:09 UTC, Soothsilver commented
I updated the wordings.

2020-10-02 13:25 UTC, gfraiteur approved these changes
I'm fine with the content (I have suggestion) but again there should be SEO optimization, i.e. the link anchors should contain keywords we're interested in.  There should also be the Google Analytics tags on both sides.

2020-10-02 13:25 UTC, gfraiteur commented on _posts/2020-09-25-conveyor.md
> +If you're developing a web application, you want to test and debug it from devices other than your development machine. In this article, we'll show how you can do that - even if the website is not ye
```suggestion
If you're developing a web application, there are times you want to test and debug it from devices other than your development machine: from a phone that's not connected to the local network,  for instance, or from an online service if you're building a webhook. In this article, we'll show how you can do that -- even if the website is not yet deployed -- and also how you can find errors in your code in such a situation with detailed automatic logging. We will be using Conveyor, a tool that [builds a tunnel between your local machine and the Internet](https://conveyor.clou) and PostSharp Logging, which [add highly detailed logging to your .NET projects with zero impact on source code](https://www.postsharp.net/logging)
```

I've added a more concrete case in the intro and added some SEO.

2020-10-02 13:25 UTC, gfraiteur commented on _posts/2020-09-25-conveyor.md
> +You could also target logging more precisely or exclude methods, classes or namespaces with [multicasting](https://doc.postsharp.net/attribute-multicasting).
```suggestion
In a real-life project, you will soon figure out that this is way too verbose. You can [select which methods, classes or namespaces to trace](https://doc.postsharp.net/attribute-multicasting) with multicasting.
```

This is better for SEO because we're not optimizing for multicasting.

2020-10-02 15:29 UTC, Soothsilver commented
We've discussed Analytics tags with Lejla, and we're asking Keyoti to add them, but they're not interested in having the tags on our blog post.

2020-10-02 15:30 UTC, merged